### ISSUE TITLE
Custom Geometry

### ISSUE THREAD

**Issue by padreon** [brokiem/SimpleNPC#1]
Custom Geometry

**Comment by Altamash347** [comment]
yeah thats a great idea

**Comment by brokiem** [comment]
You can register your own entity with custom geometry (https://github.com/brokiem/SimpleNPC#developers). Extend your entity class to [brokiem/snpc/entity/CustomHuman] and set custom skin and custom geometry

**Comment by UnEnanoMas** [comment]
@brokiem https://github.com/brokiem/CustomEntity/issues/1
