### ISSUE TITLE
commands on behalf of a player

### ISSUE THREAD

**Issue by fatstacksjack** [brokiem/SimpleNPC#12]
how would i make it open a kits menue like /kit when the player punches the npc. i use /rca but how would i make it on behalf of the player? since there is no @p like vanilla minecraft.

**Comment by nezneb0** [comment]
Do {player}

**Comment by nezneb0** [comment]
Can really close issue but **ISSUE CLOSED**

**Comment by brokiem** [comment]
use {player}
