### ISSUE TITLE
Non Human entities do not display their name tags unless they are being looked at.

### ISSUE THREAD

**Issue by cheeseland-dev** [brokiem/SimpleNPC#14]
This feature is how named entities work in vanilla, however It's largely inconvenient if you want to use non human NPCs and have them visible from far away.

Also this only sometimes happens, if you restart the server after making some it usually happens.

**Comment by brokiem** [comment]
What version of Simple NPC are you using?

**Comment by cheeseland-dev** [comment]
I'm using the one from poggit, if the issue has been fixed since then then it's my bad.

**Comment by nezneb0** [comment]
> I'm using the one from poggit, if the issue has been fixed since then then it's my bad.

He means what version like v1.0.1, 1.0.0, or 2.0.0

**Comment by cheeseland-dev** [comment]
I'm using 1.0.1-beta according to the plugin.yml

**Comment by brokiem** [comment]
Fixed in v2.0.0
