### ISSUE TITLE
Missing EasyUI Virion

### ISSUE THREAD

**Issue by cheeseland-dev** [brokiem/SimpleNPC#19]
It's a pretty simple fix, you just need to add the EasyUI folder to src, but without it people aren't able to do `/snpc edit` without getting an error.

[EasyUI.zip](https://github.com/brokiem/SimpleNPC/files/6285752/EasyUI.zip)

**Comment by brokiem** [comment]
Please download the plugin from poggit ci if the plugin is not released yet
https://poggit.pmmp.io/ci/SimpleNPC
