### ISSUE TITLE
Add Player Count in Nametags

### ISSUE THREAD

**Issue by Altamash347** [brokiem/SimpleNPC#23]
add world and server player count in the nametags of the NPC. And let us count combined worlds in a single playercount

**Comment by brokiem** [comment]
Done. You can use this external plugin
WorldPlayerCount: https://poggit.pmmp.io/ci/brokiem/SimpleNPCPlayerCount/SimpleNPCPlayerCount
SlapperPlayerCount: https://poggit.pmmp.io/ci/brokiem/SimpleNPCWorldPlayerCount/SimpleNPCWorldPlayerCount
