### ISSUE TITLE
Incompatible protocol version

### ISSUE THREAD

**Issue by DPG896** [brokiem/SimpleNPC#24]
![Screenshot_20210413-144939](https://user-images.githubusercontent.com/82310008/114508937-788a0900-9c24-11eb-9c95-334336f27b47.png)
Pleass fix it as soon as possible

**Comment by littlecaw8564** [comment]
take the new dev verssion https://poggit.pmmp.io/r/121878/SimpleNPC_dev-144.phar

**Comment by brokiem** [comment]
done in simplenpc 2.0.1
