### ISSUE TITLE
Topographic cooldown + error

### ISSUE THREAD

**Issue by UnEnanoMas** [brokiem/SimpleNPC#28]
**Describe the bug**
The deactivated cooldown does not work, it is still active (also change the name from "Coldown" to "Cooldown")

**To Reproduce**
1. Set cooldown to 0
2. restart the server
3. as soon as you enter, touch an npc and you have to wait 2 seconds

**Expected behavior**
That when you touch it, it will run without delay

**Screenshots**

**SimpleNPC plugin information**
 - Version: Dev ver 157
 - Server api: 3.19.0

**Comment by brokiem** [comment]
try this build: https://poggit.pmmp.io/r/123137/SimpleNPC_dev-159.phar

**Comment by UnEnanoMas** [comment]
working
