### ISSUE TITLE
NPCs Turns back to their original size after changing their sizes

### ISSUE THREAD

**Issue by Altamash347** [brokiem/SimpleNPC#42]
**Describe the bug**
I changed a blaze NPC's Size to 20 because I needed a big blaze, but whenever I rejoin the server, the blaze turns back to his original size

**To Reproduce**

1. Go to your Server
2. Type the command `/snpc ui`
3. Select Spawn NPC 
4. Select Blaze NPC
5. Type its name and all settings whatever and Spawn it
6. Now type `/snpc ui` again
7. press edit NPC
8. Type the ID of the Blaze NPC and press Submit
9. Now Click on Edit Size Button
10. Now change the size to 20
11. Now left the server
12. or Restart it
13. Join again
14. You will see the blaze is back to its original size

**Expected behavior**
I expected the Blaze will stay in 20 Size forever

**SimpleNPC plugin information**

- Version: Latest
- Server api: 3.19.2

**Additional context**
Please Fix this, I love this plugin. It made my life easier and You are active too.

**Comment by brokiem** [comment]
try running ```/save-all``` command before restarting the server

**Comment by Altamash347** [comment]
> try running `/save-all` command before restarting the server

Its even happening when I am leaving the server.
