### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by DardrezFxV2** [brokiem/SimpleNPC#43]
The commands doesn't work i tried all versions

**Comment by brokiem** [comment]
Without knowing your reproductive steps, SimpleNPC version, or PocketMine-MP api the issue cannot begin to be solved.

A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
