### ISSUE TITLE
NG

### ISSUE THREAD

**Issue by YOGO-VIP** [brokiem/SimpleNPC#44]
<My friend when I add my personal commands it doesn't work can you help me please.>    Thank 🌹

**Comment by brokiem** [comment]
Without knowing your reproductive steps, SimpleNPC version, or PocketMine-MP api the issue cannot begin to be solved.

A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
