### ISSUE TITLE
Animated NPCs

### ISSUE THREAD

**Issue by Altamash347** [brokiem/SimpleNPC#45]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Its not a problem

**Describe alternatives you've considered**
Animated NPCs

**Additional context**
Add like an Animated NPCs where a NPC will have bends and like a statue but animated (not talking about Emotes)

**Comment by brokiem** [comment]
This can be implemented with a plugin

**Comment by Altamash347** [comment]
> This can be implemented with a plugin

Which plugin?

**Comment by brokiem** [comment]
Make your own
