### ISSUE TITLE
Implementation of NPCDialog

### ISSUE THREAD

**Issue by benda95280** [brokiem/SimpleNPC#47]
**Is your feature request related to a problem? Please describe.**
Could it be integrated [NPCDialog](https://github.com/andresbytes/NpcDialog/tree/master/)

**Describe the solution you'd like**
Be able to set in config file of the NPC, one or more dialog (if more than one, take first, second, third, and back to first).
If possible, have custom actions on button (Null / Command ...).
If possible, support more than one button.

**Describe alternatives you've considered**
No alternative

**Additional context**
Picture taken from NPCDialog :
![image](https://user-images.githubusercontent.com/1539408/120921438-f5d17780-c6c3-11eb-9f61-6f2d3a318cfe.png)

**Comment by brokiem** [comment]
1. Create your Entity
2. Extend to BaseNPC or CustomHuman
3. Make your NPC Dialog

How to get Npc Config: [NPCManager#getConfigNPC(string: identifier);](https://github.com/brokiem/SimpleNPC/blob/master/src/brokiem/snpc/manager/NPCManager.php#L279)

**Comment by benda95280** [comment]
Was hopping to get in integrated inside the main configuration / plugin :(
