### ISSUE TITLE
mob set as npc

### ISSUE THREAD

**Issue by rem137** [brokiem/SimpleNPC#5]
I use the plugin pureentitiesx for generate mob but the simplenpc plugin set all my mob as a npc so i can't hit them and they don't moove. (sorry for my bad english)

**Comment by brokiem** [comment]
can you test with this version? https://poggit.pmmp.io/r/120284/SimpleNPC_dev-86.phar

**Comment by rem137** [comment]
okay for the moment i have no probleme it's perfect thank you

**Comment by supercrafter333** [comment]
Already fixed. Please close this Issue. :)
