### ISSUE TITLE
Skin Glitch

### ISSUE THREAD

**Issue by yangyong080228** [brokiem/SimpleNPC#64]
**Describe the bug**
NPC's Skin not working? 

**To Reproduce**

1. Spawn a First Human NPC, it will works perfectly fine.
2. Spawn another one, it's skin will be Glitched

**Expected behavior**
Skin Works?

**Screenshots**
![image](https://user-images.githubusercontent.com/71582030/125935184-93c069ad-86ab-44d3-b5a8-bd90f2694ade.png)

**SimpleNPC plugin information**

- Version: 2.1.6
- Server api: 3.220

**Additional context**
the npc's id is kinda high for some reasn

**Comment by brokiem** [comment]
between minecraft skin bug or corrupt png

**Comment by yangyong080228** [comment]
> between minecraft skin bug or corrupted png

wut

**Comment by RealBJsingh** [comment]
Skin are getting glitched because its a minecraft bug

**Comment by yangyong080228** [comment]
oh thanks for the translate

**Comment by yangyong080228** [comment]
How can I fix it tho :/

**Comment by brokiem** [comment]
change to another skin and blame mojang
