### ISSUE TITLE
How to make NPC's Walk

### ISSUE THREAD

**Issue by ElectroGamesYT** [brokiem/SimpleNPC#70]
Hello, how do I make the NPC's Walk?
I see it is a feature! :D

**Comment by brokiem** [comment]
spawn a walking npc

**Comment by ElectroGamesYT** [comment]
Please re read my message once again. I think you misread it. I was asking how do I do it.

**Comment by llPushkarSinghll** [comment]
> Please re read my message once again. I think you misread it. I was asking how do I do it.

Use " /snpc ui "and ui will open then u can see all the spawning options and tap on walking npc option then put name and tap on summit then it will spawn then enjoy it 🙂
