### ISSUE TITLE
You steal all plugins 😂😂

### ISSUE THREAD

**Issue by MadooxMc** [brokiem/SimpleNPC#73]
Oh ookkkk i know you re not real devloper you don’t understand anything you are the creator of plugin simple pet, steal of complex pets😂😂 i understand better why you don’t answer me

**Comment by brokiem** [comment]
just dont use my plugins

**Comment by Vecnavium** [comment]
Your just stupid tbh, he is a developer and your other opened issue was honestly stupud as well, the plugin works on API 3 and is compatible.

**Comment by MadooxMc** [comment]
You are more stupid than me because you insult me and i am frustred because anyone answer me, is an good reason to clash you

**Comment by MadooxMc** [comment]
i used all your plugins 😁
