### ISSUE TITLE
SimpleNPC 1.18 Bug

### ISSUE THREAD

**Issue by ghost** [brokiem/SimpleNPC#78]
Can you make a update for Pocketmine MP: 3.26.0 (1.18), 3.26.1 (1.18) and 4.0.0 (1.18) Thanks

**Comment by TioBlazerzin** [comment]
Você pode fazer uma atualização para Pocketmine MP: 3.26.0 (1.18), 3.26.1 (1.18) e 4.0.0 (1.18) Obrigado

**Comment by ghost** [comment]
I have already and it doesn't work still.
