### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by rem137** [brokiem/SimpleNPC#8]
can you do something for set the skin to the skin of a player of the server ?

**Comment by brokiem** [comment]
Done in this commit (https://github.com/brokiem/SimpleNPC/commit/057279ee5b6adbe1266f8402e1f341a60b96686f#diff-88d4163480867d11374dba9f2667d610d2d9656e2b3e82ea23a6bbff4c654f96R222-R230) you must edit the npc
