### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by cherrychip8293** [brokiem/SimpleNPC#80]
InvalidArgumentException: "skin is not a valid element identifier" (EXCEPTION) in "/root/pm/virions/EasyUI-master/src/EasyUI/utils/FormResponse" at line 67
--- Stack trace ---
  #0 /root/pm/virions/EasyUI-master/src/EasyUI/utils/FormResponse(40): EasyUI\utils\FormResponse->getElement(string[4] skin, string[20] EasyUI\element\Input)
  #1 plugins/SimpleNPC-pm4-new/src/brokiem/snpc/manager/form/FormManager(99): EasyUI\utils\FormResponse->getInputSubmittedText(string[4] skin)
  #2 /root/pm/virions/EasyUI-master/src/EasyUI/variant/CustomForm(64): brokiem\snpc\manager\form\FormManager->brokiem\snpc\manager\form\{closure}(object pocketmine\player\Player#25461, object EasyUI\utils\FormResponse#114827)  #3 /root/pm/virions/EasyUI-master/src/EasyUI/variant/CustomForm(84): EasyUI\variant\CustomForm->executeSubmitListener(object pocketmine\player\Player#25461, object EasyUI\utils\FormResponse#114827)
  #4 pmsrc/src/player/Player(1913): EasyUI\variant\CustomForm->handleResponse(object pocketmine\player\Player#25461, array[2])
  #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(846): pocketmine\player\Player->onFormSubmit(integer 2, array[2])
  #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#114964)
  #7 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#94824)
  #8 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#114964, string[19] e..[0,"........."].)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[22] .Ne..6.Qz....k....J.\.)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[31] .......H.n@.M..<.....K?........)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#25037)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/src/Server(1657): pocketmine\snooze\SleeperHandler->sleepUntil(double 1642950175.8274)
  #15 pmsrc/src/Server(1044): pocketmine\Server->tickProcessor()
  #16 pmsrc/src/PocketMine(303): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[9] /root/pm/, string[17] /root/pm/plugins/)
  #17 pmsrc/src/PocketMine(326): pocketmine\server()
  #18 pmsrc(11): require(string[53] phar:///root/pm/PocketMine-MP.phar/src/PocketMine.php)

**Comment by brokiem** [comment]
please download plugin from poggit stable release
