### ISSUE TITLE
transfer server not working

### ISSUE THREAD

**Issue by MayCantCode** [brokiem/SimpleNPC#81]
when i downloaded the plugin for 1.18 from youtube and it worked but when i enter command to go another server it says in console player not found

**Comment by Pinkglitter2216** [comment]
Darf ich dazu auch eine Frage stellen? Wie fügen sie den transferserver command dem npc zu? Bei mir funktioniert das nämlich gar nicht...

**Comment by MayCantCode** [comment]
Hey I didn't understand the mail u send me as I speak English only

**Comment by Pinkglitter2216** [comment]
Oh Sorry.. I have also a question to the npc plugin. How do you add the transfer server command to the NPC? It doesn't work at all for me...

**Comment by MayCantCode** [comment]
It is -
rca {player} tranferserver IP port
But some problem with the the new development version as It says player not
found in console

**Comment by brokiem** [comment]
should be fixed in next 3.0.1
