### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gamegam** [brokiem/SimpleNPC#82]
[03:09:30.037] [Server thread/CRITICAL]: InvalidArgumentException: "snpcid_edit is not a valid element identifier" (EXCEPTION) in "C:/Users/Administrator/Desktop/server/virions/EasyUI-master/src/EasyUI/utils/FormResponse" at line 67
--- Stack trace ---
  #0 C:/Users/Administrator/Desktop/server/virions/EasyUI-master/src/EasyUI/utils/FormResponse(40): EasyUI\utils\FormResponse->getElement(string[11] snpcid_edit, string[20] EasyUI\element\Input)
  #1 plugins/SimpleNPC-pm4-new/src/brokiem/snpc/manager/form/FormManager(100): EasyUI\utils\FormResponse->getInputSubmittedText(string[11] snpcid_edit)
  #2 C:/Users/Administrator/Desktop/server/virions/EasyUI-master/src/EasyUI/variant/CustomForm(64): brokiem\snpc\manager\form\FormManager->brokiem\snpc\manager\form\{closure}(object pocketmine\player\Player#30216, object EasyUI\utils\FormResponse#119026)
  #3 C:/Users/Administrator/Desktop/server/virions/EasyUI-master/src/EasyUI/variant/CustomForm(84): EasyUI\variant\CustomForm->executeSubmitListener(object pocketmine\player\Player#30216, object EasyUI\utils\FormResponse#119026)
  #4 pmsrc/src/player/Player(1985): EasyUI\variant\CustomForm->handleResponse(object pocketmine\player\Player#30216, array[3])
  #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(892): pocketmine\player\Player->onFormSubmit(integer 2, array[3])
  #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#120931)
  #7 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#95613)
  #8 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#120931, string[29] e..[0,"............","null"].)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[33] .Me..6.Qz3o...-o.nx;u...R^iN.R,..)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[42] .....F..c.y....7....hO.Q.Ym.L.[j.m.-..U..O)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#28632)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644520170.0494)
  #15 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #16 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[38] C:\Users\Administrator\Desktop\server\, string[46] C:\Users\Administrator\Desktop\server\plugins\)
  #17 pmsrc/src/PocketMine(327): pocketmine\server()
  #18 pmsrc(11): require(string[82] phar://C:/Users/Administrator/Desktop/server/PocketMine-MP.phar/src/PocketMine.p)
--- End of exception information ---
[03:09:30.037] [Server thread/EMERGENCY]: 복구 불가능한 오류가 발생하여 서버가 충돌했습니다. 충돌 덤프를 만듭니다
[03:09:30.048] [Server thread/EMERGENCY]: "C:/Users/Administrator/Desktop/server/crashdumps/Thu_Feb_10-19.09.30-UTC_2022.log" 파일을 충돌 보관소에 업로드하고 버그 보고 페이지에 링크를 제출해주세요. 가능한 한 많은 정보를 주시기 바랍니다.
[03:09:31.268] [Server thread/EMERGENCY]: 충돌 덤프가 자동으로 충돌 보관소에 제출되었습니다. https://crash.pmmp.io/view/5914391에서 보거나 ID #5914391을(를) 사용할 수 있습니다.
[03:09:31.272] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by brokiem** [comment]
please download plugin from poggit stable release
