### ISSUE TITLE
Weird bug that is so annoying 

### ISSUE THREAD

**Issue by Tuvqlu** [brokiem/SimpleNPC#83]
**Describe the bug**
THESE TWO NPCS KEEP DISSAPPEARING, and everything else is still there

**To Reproduce**
I ACTUALLY DK:

**Expected behavior**
 NOT HAVING TO ENTER THE SAMENPC 2030 times .

**Screenshots**
.

**SimpleNPC plugin information**

- Version: [e.g. 3.0.1]
- Server api: [e.g. 3.
- 
4.2]

**Additional context**

help.

**Comment by brokiem** [comment]
duplicate #66
