### ISSUE TITLE
How to set npc transfer server for members

### ISSUE THREAD

**Issue by MayCantCode** [brokiem/SimpleNPC#85]
Hey,
When people click on the npc in my server that has to transfer them to another server . They get a message that u don't have permission to use transferserver command pls help

**Comment by MrBlasyMSK** [comment]
> Hey, When people click on the npc in my server that has to transfer them to another server . They get a message that u don't have permission to use transferserver command pls help

Add this permission to the group or player that you want to be transferred
`pocketmine.command.transferserver`

And close the issue

**Comment by MayCantCode** [comment]
Ok thanks but how do i setup for anyone that join server has permision

**Comment by scamaccas** [comment]
> Ok thanks but how do i setup for anyone that join server has permision

make a groups and add permission
