### ISSUE TITLE
cant connect to multi world tp

### ISSUE THREAD

**Issue by Prex9090** [brokiem/SimpleNPC#87]
helloooo, how to fix cant connect to multi world tp only clikable huhu can u plss help me add me in discord to help im always active.  pol_Dumpstairz#2291 thanks

**Comment by MrBlasyMSK** [comment]
addcommand > {player} mw tp pvpworld

**Comment by Prex9090** [comment]
heyyy this is the proof

**Comment by Prex9090** [comment]
https://user-images.githubusercontent.com/102614294/161394491-12423bed-a20b-428f-9447-9e60d95284c3.mp4

hey this is the prooff. pls help me

**Comment by Prex9090** [comment]
> {player}

STILL CANNTTT

**Comment by MrBlasyMSK** [comment]
copy and paste:
`{player} mw tp changethisforthenameworld`

**Comment by Prex9090** [comment]
> 

plssss help me @discord plssss ill send you more proof. here cannot send coz limit

**Comment by SayaAEP** [comment]
> {player} mw tp pvpworld

wrong

`mw tp pvpworld {player}`



> > 
> 
> plssss help me @discord plssss ill send you more proof. here cannot send coz limit

`mw tp pvpworld {player}`
if you `rca {player] mw tp pvpworld`. the player cant tp cuz player dont have permision
