### ISSUE TITLE
Enderman = Bat

### ISSUE THREAD

**Issue by TukangM** [brokiem/SimpleNPC#88]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/91467886/163391439-9eb110fe-50bb-4746-85cb-2a3117756760.png)

**SimpleNPC plugin information**

- Version: [e.g. 3.0.1]
- Server api: [e.g. 4.2.6]

**Additional context**
i want spawn enderman npc but snpc spawn bat npc

**Comment by brokiem** [comment]
https://github.com/brokiem/SimpleNPC/blob/pm4-new/src/brokiem/snpc/entity/npc/EndermanNPC.php#L26 banggod 
ill fix it later
