### ISSUE TITLE
Skin Bug

### ISSUE THREAD

**Issue by DaDevGuy** [brokiem/SimpleNPC#91]
**Describe the bug**
So Actually I Have Skins In My Texture Pack, But Whenever I provides The Path Of Skin At Always Give Me Error **(Only Png Is Supported)** even my skins are in png

**To Reproduce**
1. Run Command `/snpc ui`
2. Click Human Npc
3. Type Any Name Of Npc
4. put path of skin
5. Error Will Appear

**Expected behavior**
Should Create A Npc with path of skin.

**Screenshots**

**SimpleNPC plugin information**

- Latest SimpleNPC Version
- Latest Server Version

**Additional context**

**Comment by brokiem** [comment]
you must use raw url. ex: https://s.namemc.com/i/b6d3866c563b3d14.png
