### ISSUE TITLE
Random Npc Dissappearing

### ISSUE THREAD

**Issue by Tuvqlu** [brokiem/SimpleNPC#97]
**Describe the bug**
So I have a lot of NPCS. Earlier today half of them just disappeared and when I place an a NPC back it disappears.

**To Reproduce**
Create NPC and Relog 

**Expected behavior**
my npcs to not disappear 

**SimpleNPC plugin information**

- Version: [e.g. 4.01]
- Server api: [e.g. 1.19.21]

**Additional context**

**Comment by brokiem** [comment]
Should be fixed in v4.0.1
