### ISSUE TITLE
Remove console feedback when run command with NPC

### ISSUE THREAD

**Issue by husencoolwolf** [brokiem/SimpleNPC#98]
**Is your feature request related to a problem? Please describe.**
Its problem when play on Mobile version. It block some significant view.

**How to produce**
- Spawn NPC
- Add Command example : give {player} diamond_boots
- submit command
- Hit NPC to run command

**Problem**
Every one person run command, All player on server get his console feedback
Picture : [https://imgur.com/AItlc9Z]

**Describe the solution you'd like**
i hope console feedback will be hidden to other player. 

**Describe alternatives you've considered**
At least only the player that run command seeing console feedback. not other player

Thanks

**Comment by brokiem** [comment]
The console message is from pocketmine **when you are an operator**, nothing to do with simple npc.
